package curves

import (
	"fmt"
	"github.com/golang/protobuf/proto"
	"math"
)

// Code generated by protoc-gen-go. DO NOT EDIT.
// source: curves_elements.proto

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type GameOverEvent_Team int32

const (
	GameOverEvent_UNKNOWN GameOverEvent_Team = 0
	GameOverEvent_TEAM_1  GameOverEvent_Team = 1
	GameOverEvent_TEAM_2  GameOverEvent_Team = 2
)

var GameOverEvent_Team_name = map[int32]string{
	0: "UNKNOWN",
	1: "TEAM_1",
	2: "TEAM_2",
}

var GameOverEvent_Team_value = map[string]int32{
	"UNKNOWN": 0,
	"TEAM_1":  1,
	"TEAM_2":  2,
}

func (x GameOverEvent_Team) String() string {
	return proto.EnumName(GameOverEvent_Team_name, int32(x))
}

func (GameOverEvent_Team) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_4bd39486e62a5f01, []int{3, 0}
}

type Curve_CurveType int32

const (
	Curve_UNKNOWN               Curve_CurveType = 0
	Curve_CIRCULAR_LINEAR_CURVE Curve_CurveType = 1
	Curve_COLOR_CURVE           Curve_CurveType = 2
	Curve_LINEAR_CURVE          Curve_CurveType = 3
	Curve_LINEAR_VECTOR_CURVE   Curve_CurveType = 4
	Curve_PULSE_CURVE           Curve_CurveType = 5
	Curve_STEP_CURVE            Curve_CurveType = 6
	Curve_STEP_VECTOR_CURVE     Curve_CurveType = 7
	Curve_MESSAGE_CURVE         Curve_CurveType = 8
)

var Curve_CurveType_name = map[int32]string{
	0: "UNKNOWN",
	1: "CIRCULAR_LINEAR_CURVE",
	2: "COLOR_CURVE",
	3: "LINEAR_CURVE",
	4: "LINEAR_VECTOR_CURVE",
	5: "PULSE_CURVE",
	6: "STEP_CURVE",
	7: "STEP_VECTOR_CURVE",
	8: "MESSAGE_CURVE",
}

var Curve_CurveType_value = map[string]int32{
	"UNKNOWN":               0,
	"CIRCULAR_LINEAR_CURVE": 1,
	"COLOR_CURVE":           2,
	"LINEAR_CURVE":          3,
	"LINEAR_VECTOR_CURVE":   4,
	"PULSE_CURVE":           5,
	"STEP_CURVE":            6,
	"STEP_VECTOR_CURVE":     7,
	"MESSAGE_CURVE":         8,
}

func (x Curve_CurveType) String() string {
	return proto.EnumName(Curve_CurveType_name, int32(x))
}

func (Curve_CurveType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_4bd39486e62a5f01, []int{4, 0}
}

type CircularLinearPoint_CircularLinearType int32

const (
	CircularLinearPoint_UNKNOWN CircularLinearPoint_CircularLinearType = 0
	CircularLinearPoint_L       CircularLinearPoint_CircularLinearType = 1
	CircularLinearPoint_C       CircularLinearPoint_CircularLinearType = 2
	CircularLinearPoint_CM      CircularLinearPoint_CircularLinearType = 3
	CircularLinearPoint_CMC     CircularLinearPoint_CircularLinearType = 4
)

var CircularLinearPoint_CircularLinearType_name = map[int32]string{
	0: "UNKNOWN",
	1: "L",
	2: "C",
	3: "CM",
	4: "CMC",
}

var CircularLinearPoint_CircularLinearType_value = map[string]int32{
	"UNKNOWN": 0,
	"L":       1,
	"C":       2,
	"CM":      3,
	"CMC":     4,
}

func (x CircularLinearPoint_CircularLinearType) String() string {
	return proto.EnumName(CircularLinearPoint_CircularLinearType_name, int32(x))
}

func (CircularLinearPoint_CircularLinearType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_4bd39486e62a5f01, []int{6, 0}
}

type Element struct {
	// Types that are valid to be assigned to E:
	//	*Element_InitialDataEvent
	//	*Element_CreateEntityEvent
	//	*Element_GameOverEvent
	//	*Element_Curve
	//	*Element_PulsePoint
	//	*Element_CircularLinearPoint
	//	*Element_ColorPoint
	//	*Element_BasicPoint
	//	*Element_VectorPoint
	//	*Element_MessagePoint
	E                    isElement_E `protobuf_oneof:"e"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *Element) Reset()         { *m = Element{} }
func (m *Element) String() string { return proto.CompactTextString(m) }
func (*Element) ProtoMessage()    {}
func (*Element) Descriptor() ([]byte, []int) {
	return fileDescriptor_4bd39486e62a5f01, []int{0}
}

func (m *Element) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Element.Unmarshal(m, b)
}
func (m *Element) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Element.Marshal(b, m, deterministic)
}
func (m *Element) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Element.Merge(m, src)
}
func (m *Element) XXX_Size() int {
	return xxx_messageInfo_Element.Size(m)
}
func (m *Element) XXX_DiscardUnknown() {
	xxx_messageInfo_Element.DiscardUnknown(m)
}

var xxx_messageInfo_Element proto.InternalMessageInfo

type isElement_E interface {
	isElement_E()
}

type Element_InitialDataEvent struct {
	InitialDataEvent *InitialDataEvent `protobuf:"bytes,1,opt,name=initialDataEvent,proto3,oneof"`
}

type Element_CreateEntityEvent struct {
	CreateEntityEvent *CreateEntityEvent `protobuf:"bytes,2,opt,name=createEntityEvent,proto3,oneof"`
}

type Element_GameOverEvent struct {
	GameOverEvent *GameOverEvent `protobuf:"bytes,3,opt,name=gameOverEvent,proto3,oneof"`
}

type Element_Curve struct {
	Curve *Curve `protobuf:"bytes,4,opt,name=curve,proto3,oneof"`
}

type Element_PulsePoint struct {
	PulsePoint *PulsePoint `protobuf:"bytes,5,opt,name=pulsePoint,proto3,oneof"`
}

type Element_CircularLinearPoint struct {
	CircularLinearPoint *CircularLinearPoint `protobuf:"bytes,6,opt,name=circularLinearPoint,proto3,oneof"`
}

type Element_ColorPoint struct {
	ColorPoint *ColorPoint `protobuf:"bytes,7,opt,name=colorPoint,proto3,oneof"`
}

type Element_BasicPoint struct {
	BasicPoint *BasicPoint `protobuf:"bytes,8,opt,name=basicPoint,proto3,oneof"`
}

type Element_VectorPoint struct {
	VectorPoint *VectorPoint `protobuf:"bytes,9,opt,name=vectorPoint,proto3,oneof"`
}

type Element_MessagePoint struct {
	MessagePoint *MessagePoint `protobuf:"bytes,10,opt,name=messagePoint,proto3,oneof"`
}

func (*Element_InitialDataEvent) isElement_E() {}

func (*Element_CreateEntityEvent) isElement_E() {}

func (*Element_GameOverEvent) isElement_E() {}

func (*Element_Curve) isElement_E() {}

func (*Element_PulsePoint) isElement_E() {}

func (*Element_CircularLinearPoint) isElement_E() {}

func (*Element_ColorPoint) isElement_E() {}

func (*Element_BasicPoint) isElement_E() {}

func (*Element_VectorPoint) isElement_E() {}

func (*Element_MessagePoint) isElement_E() {}

func (m *Element) GetE() isElement_E {
	if m != nil {
		return m.E
	}
	return nil
}

func (m *Element) GetInitialDataEvent() *InitialDataEvent {
	if x, ok := m.GetE().(*Element_InitialDataEvent); ok {
		return x.InitialDataEvent
	}
	return nil
}

func (m *Element) GetCreateEntityEvent() *CreateEntityEvent {
	if x, ok := m.GetE().(*Element_CreateEntityEvent); ok {
		return x.CreateEntityEvent
	}
	return nil
}

func (m *Element) GetGameOverEvent() *GameOverEvent {
	if x, ok := m.GetE().(*Element_GameOverEvent); ok {
		return x.GameOverEvent
	}
	return nil
}

func (m *Element) GetCurve() *Curve {
	if x, ok := m.GetE().(*Element_Curve); ok {
		return x.Curve
	}
	return nil
}

func (m *Element) GetPulsePoint() *PulsePoint {
	if x, ok := m.GetE().(*Element_PulsePoint); ok {
		return x.PulsePoint
	}
	return nil
}

func (m *Element) GetCircularLinearPoint() *CircularLinearPoint {
	if x, ok := m.GetE().(*Element_CircularLinearPoint); ok {
		return x.CircularLinearPoint
	}
	return nil
}

func (m *Element) GetColorPoint() *ColorPoint {
	if x, ok := m.GetE().(*Element_ColorPoint); ok {
		return x.ColorPoint
	}
	return nil
}

func (m *Element) GetBasicPoint() *BasicPoint {
	if x, ok := m.GetE().(*Element_BasicPoint); ok {
		return x.BasicPoint
	}
	return nil
}

func (m *Element) GetVectorPoint() *VectorPoint {
	if x, ok := m.GetE().(*Element_VectorPoint); ok {
		return x.VectorPoint
	}
	return nil
}

func (m *Element) GetMessagePoint() *MessagePoint {
	if x, ok := m.GetE().(*Element_MessagePoint); ok {
		return x.MessagePoint
	}
	return nil
}

// XXX_OneofFuncs is for the internal use of the proto package.
func (*Element) XXX_OneofFuncs() (func(msg proto.Message, b *proto.Buffer) error, func(msg proto.Message, tag, wire int, b *proto.Buffer) (bool, error), func(msg proto.Message) (n int), []interface{}) {
	return _Element_OneofMarshaler, _Element_OneofUnmarshaler, _Element_OneofSizer, []interface{}{
		(*Element_InitialDataEvent)(nil),
		(*Element_CreateEntityEvent)(nil),
		(*Element_GameOverEvent)(nil),
		(*Element_Curve)(nil),
		(*Element_PulsePoint)(nil),
		(*Element_CircularLinearPoint)(nil),
		(*Element_ColorPoint)(nil),
		(*Element_BasicPoint)(nil),
		(*Element_VectorPoint)(nil),
		(*Element_MessagePoint)(nil),
	}
}

func _Element_OneofMarshaler(msg proto.Message, b *proto.Buffer) error {
	m := msg.(*Element)
	// e
	switch x := m.E.(type) {
	case *Element_InitialDataEvent:
		b.EncodeVarint(1<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.InitialDataEvent); err != nil {
			return err
		}
	case *Element_CreateEntityEvent:
		b.EncodeVarint(2<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.CreateEntityEvent); err != nil {
			return err
		}
	case *Element_GameOverEvent:
		b.EncodeVarint(3<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.GameOverEvent); err != nil {
			return err
		}
	case *Element_Curve:
		b.EncodeVarint(4<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.Curve); err != nil {
			return err
		}
	case *Element_PulsePoint:
		b.EncodeVarint(5<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.PulsePoint); err != nil {
			return err
		}
	case *Element_CircularLinearPoint:
		b.EncodeVarint(6<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.CircularLinearPoint); err != nil {
			return err
		}
	case *Element_ColorPoint:
		b.EncodeVarint(7<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.ColorPoint); err != nil {
			return err
		}
	case *Element_BasicPoint:
		b.EncodeVarint(8<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.BasicPoint); err != nil {
			return err
		}
	case *Element_VectorPoint:
		b.EncodeVarint(9<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.VectorPoint); err != nil {
			return err
		}
	case *Element_MessagePoint:
		b.EncodeVarint(10<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.MessagePoint); err != nil {
			return err
		}
	case nil:
	default:
		return fmt.Errorf("Element.E has unexpected type %T", x)
	}
	return nil
}

func _Element_OneofUnmarshaler(msg proto.Message, tag, wire int, b *proto.Buffer) (bool, error) {
	m := msg.(*Element)
	switch tag {
	case 1: // e.initialDataEvent
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(InitialDataEvent)
		err := b.DecodeMessage(msg)
		m.E = &Element_InitialDataEvent{msg}
		return true, err
	case 2: // e.createEntityEvent
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(CreateEntityEvent)
		err := b.DecodeMessage(msg)
		m.E = &Element_CreateEntityEvent{msg}
		return true, err
	case 3: // e.gameOverEvent
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(GameOverEvent)
		err := b.DecodeMessage(msg)
		m.E = &Element_GameOverEvent{msg}
		return true, err
	case 4: // e.curve
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(Curve)
		err := b.DecodeMessage(msg)
		m.E = &Element_Curve{msg}
		return true, err
	case 5: // e.pulsePoint
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(PulsePoint)
		err := b.DecodeMessage(msg)
		m.E = &Element_PulsePoint{msg}
		return true, err
	case 6: // e.circularLinearPoint
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(CircularLinearPoint)
		err := b.DecodeMessage(msg)
		m.E = &Element_CircularLinearPoint{msg}
		return true, err
	case 7: // e.colorPoint
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(ColorPoint)
		err := b.DecodeMessage(msg)
		m.E = &Element_ColorPoint{msg}
		return true, err
	case 8: // e.basicPoint
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(BasicPoint)
		err := b.DecodeMessage(msg)
		m.E = &Element_BasicPoint{msg}
		return true, err
	case 9: // e.vectorPoint
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(VectorPoint)
		err := b.DecodeMessage(msg)
		m.E = &Element_VectorPoint{msg}
		return true, err
	case 10: // e.messagePoint
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(MessagePoint)
		err := b.DecodeMessage(msg)
		m.E = &Element_MessagePoint{msg}
		return true, err
	default:
		return false, nil
	}
}

func _Element_OneofSizer(msg proto.Message) (n int) {
	m := msg.(*Element)
	// e
	switch x := m.E.(type) {
	case *Element_InitialDataEvent:
		s := proto.Size(x.InitialDataEvent)
		n += 1 // tag and wire
		n += proto.SizeVarint(uint64(s))
		n += s
	case *Element_CreateEntityEvent:
		s := proto.Size(x.CreateEntityEvent)
		n += 1 // tag and wire
		n += proto.SizeVarint(uint64(s))
		n += s
	case *Element_GameOverEvent:
		s := proto.Size(x.GameOverEvent)
		n += 1 // tag and wire
		n += proto.SizeVarint(uint64(s))
		n += s
	case *Element_Curve:
		s := proto.Size(x.Curve)
		n += 1 // tag and wire
		n += proto.SizeVarint(uint64(s))
		n += s
	case *Element_PulsePoint:
		s := proto.Size(x.PulsePoint)
		n += 1 // tag and wire
		n += proto.SizeVarint(uint64(s))
		n += s
	case *Element_CircularLinearPoint:
		s := proto.Size(x.CircularLinearPoint)
		n += 1 // tag and wire
		n += proto.SizeVarint(uint64(s))
		n += s
	case *Element_ColorPoint:
		s := proto.Size(x.ColorPoint)
		n += 1 // tag and wire
		n += proto.SizeVarint(uint64(s))
		n += s
	case *Element_BasicPoint:
		s := proto.Size(x.BasicPoint)
		n += 1 // tag and wire
		n += proto.SizeVarint(uint64(s))
		n += s
	case *Element_VectorPoint:
		s := proto.Size(x.VectorPoint)
		n += 1 // tag and wire
		n += proto.SizeVarint(uint64(s))
		n += s
	case *Element_MessagePoint:
		s := proto.Size(x.MessagePoint)
		n += 1 // tag and wire
		n += proto.SizeVarint(uint64(s))
		n += s
	case nil:
	default:
		panic(fmt.Sprintf("proto: unexpected type %T in oneof", x))
	}
	return n
}

// Events
type InitialDataEvent struct {
	MapWidth             float32           `protobuf:"fixed32,1,opt,name=mapWidth,proto3" json:"mapWidth,omitempty"`
	MapHeight            float32           `protobuf:"fixed32,2,opt,name=mapHeight,proto3" json:"mapHeight,omitempty"`
	Username1            string            `protobuf:"bytes,3,opt,name=username1,proto3" json:"username1,omitempty"`
	Username2            string            `protobuf:"bytes,4,opt,name=username2,proto3" json:"username2,omitempty"`
	GameDuration         float32           `protobuf:"fixed32,5,opt,name=gameDuration,proto3" json:"gameDuration,omitempty"`
	Health               float32           `protobuf:"fixed32,7,opt,name=health,proto3" json:"health,omitempty"`
	ViewingAreaLength    float32           `protobuf:"fixed32,9,opt,name=viewingAreaLength,proto3" json:"viewingAreaLength,omitempty"`
	ViewingAreaWidth     float32           `protobuf:"fixed32,10,opt,name=viewingAreaWidth,proto3" json:"viewingAreaWidth,omitempty"`
	ViewingAreaOffset    float32           `protobuf:"fixed32,11,opt,name=viewingAreaOffset,proto3" json:"viewingAreaOffset,omitempty"`
	Background           *ColorPoint_Color `protobuf:"bytes,12,opt,name=background,proto3" json:"background,omitempty"`
	NBulletsInMagazine   int32             `protobuf:"varint,13,opt,name=nBulletsInMagazine,proto3" json:"nBulletsInMagazine,omitempty"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *InitialDataEvent) Reset()         { *m = InitialDataEvent{} }
func (m *InitialDataEvent) String() string { return proto.CompactTextString(m) }
func (*InitialDataEvent) ProtoMessage()    {}
func (*InitialDataEvent) Descriptor() ([]byte, []int) {
	return fileDescriptor_4bd39486e62a5f01, []int{1}
}

func (m *InitialDataEvent) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_InitialDataEvent.Unmarshal(m, b)
}
func (m *InitialDataEvent) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_InitialDataEvent.Marshal(b, m, deterministic)
}
func (m *InitialDataEvent) XXX_Merge(src proto.Message) {
	xxx_messageInfo_InitialDataEvent.Merge(m, src)
}
func (m *InitialDataEvent) XXX_Size() int {
	return xxx_messageInfo_InitialDataEvent.Size(m)
}
func (m *InitialDataEvent) XXX_DiscardUnknown() {
	xxx_messageInfo_InitialDataEvent.DiscardUnknown(m)
}

var xxx_messageInfo_InitialDataEvent proto.InternalMessageInfo

func (m *InitialDataEvent) GetMapWidth() float32 {
	if m != nil {
		return m.MapWidth
	}
	return 0
}

func (m *InitialDataEvent) GetMapHeight() float32 {
	if m != nil {
		return m.MapHeight
	}
	return 0
}

func (m *InitialDataEvent) GetUsername1() string {
	if m != nil {
		return m.Username1
	}
	return ""
}

func (m *InitialDataEvent) GetUsername2() string {
	if m != nil {
		return m.Username2
	}
	return ""
}

func (m *InitialDataEvent) GetGameDuration() float32 {
	if m != nil {
		return m.GameDuration
	}
	return 0
}

func (m *InitialDataEvent) GetHealth() float32 {
	if m != nil {
		return m.Health
	}
	return 0
}

func (m *InitialDataEvent) GetViewingAreaLength() float32 {
	if m != nil {
		return m.ViewingAreaLength
	}
	return 0
}

func (m *InitialDataEvent) GetViewingAreaWidth() float32 {
	if m != nil {
		return m.ViewingAreaWidth
	}
	return 0
}

func (m *InitialDataEvent) GetViewingAreaOffset() float32 {
	if m != nil {
		return m.ViewingAreaOffset
	}
	return 0
}

func (m *InitialDataEvent) GetBackground() *ColorPoint_Color {
	if m != nil {
		return m.Background
	}
	return nil
}

func (m *InitialDataEvent) GetNBulletsInMagazine() int32 {
	if m != nil {
		return m.NBulletsInMagazine
	}
	return 0
}

type CreateEntityEvent struct {
	Eid                  int32    `protobuf:"varint,1,opt,name=eid,proto3" json:"eid,omitempty"`
	Type                 string   `protobuf:"bytes,2,opt,name=type,proto3" json:"type,omitempty"`
	Team                 string   `protobuf:"bytes,3,opt,name=team,proto3" json:"team,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateEntityEvent) Reset()         { *m = CreateEntityEvent{} }
func (m *CreateEntityEvent) String() string { return proto.CompactTextString(m) }
func (*CreateEntityEvent) ProtoMessage()    {}
func (*CreateEntityEvent) Descriptor() ([]byte, []int) {
	return fileDescriptor_4bd39486e62a5f01, []int{2}
}

func (m *CreateEntityEvent) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateEntityEvent.Unmarshal(m, b)
}
func (m *CreateEntityEvent) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateEntityEvent.Marshal(b, m, deterministic)
}
func (m *CreateEntityEvent) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateEntityEvent.Merge(m, src)
}
func (m *CreateEntityEvent) XXX_Size() int {
	return xxx_messageInfo_CreateEntityEvent.Size(m)
}
func (m *CreateEntityEvent) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateEntityEvent.DiscardUnknown(m)
}

var xxx_messageInfo_CreateEntityEvent proto.InternalMessageInfo

func (m *CreateEntityEvent) GetEid() int32 {
	if m != nil {
		return m.Eid
	}
	return 0
}

func (m *CreateEntityEvent) GetType() string {
	if m != nil {
		return m.Type
	}
	return ""
}

func (m *CreateEntityEvent) GetTeam() string {
	if m != nil {
		return m.Team
	}
	return ""
}

type GameOverEvent struct {
	T                    float32            `protobuf:"fixed32,1,opt,name=t,proto3" json:"t,omitempty"`
	Winner               GameOverEvent_Team `protobuf:"varint,2,opt,name=winner,proto3,enum=curves.GameOverEvent_Team" json:"winner,omitempty"`
	Bot1CrashTime        float32            `protobuf:"fixed32,3,opt,name=bot1CrashTime,proto3" json:"bot1CrashTime,omitempty"`
	Bot2CrashTime        float32            `protobuf:"fixed32,4,opt,name=bot2CrashTime,proto3" json:"bot2CrashTime,omitempty"`
	XXX_NoUnkeyedLiteral struct{}           `json:"-"`
	XXX_unrecognized     []byte             `json:"-"`
	XXX_sizecache        int32              `json:"-"`
}

func (m *GameOverEvent) Reset()         { *m = GameOverEvent{} }
func (m *GameOverEvent) String() string { return proto.CompactTextString(m) }
func (*GameOverEvent) ProtoMessage()    {}
func (*GameOverEvent) Descriptor() ([]byte, []int) {
	return fileDescriptor_4bd39486e62a5f01, []int{3}
}

func (m *GameOverEvent) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GameOverEvent.Unmarshal(m, b)
}
func (m *GameOverEvent) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GameOverEvent.Marshal(b, m, deterministic)
}
func (m *GameOverEvent) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GameOverEvent.Merge(m, src)
}
func (m *GameOverEvent) XXX_Size() int {
	return xxx_messageInfo_GameOverEvent.Size(m)
}
func (m *GameOverEvent) XXX_DiscardUnknown() {
	xxx_messageInfo_GameOverEvent.DiscardUnknown(m)
}

var xxx_messageInfo_GameOverEvent proto.InternalMessageInfo

func (m *GameOverEvent) GetT() float32 {
	if m != nil {
		return m.T
	}
	return 0
}

func (m *GameOverEvent) GetWinner() GameOverEvent_Team {
	if m != nil {
		return m.Winner
	}
	return GameOverEvent_UNKNOWN
}

func (m *GameOverEvent) GetBot1CrashTime() float32 {
	if m != nil {
		return m.Bot1CrashTime
	}
	return 0
}

func (m *GameOverEvent) GetBot2CrashTime() float32 {
	if m != nil {
		return m.Bot2CrashTime
	}
	return 0
}

type Curve struct {
	Eid                  int32           `protobuf:"varint,1,opt,name=eid,proto3" json:"eid,omitempty"`
	Id                   int32           `protobuf:"varint,2,opt,name=id,proto3" json:"id,omitempty"`
	Ctype                Curve_CurveType `protobuf:"varint,3,opt,name=ctype,proto3,enum=curves.Curve_CurveType" json:"ctype,omitempty"`
	Type                 string          `protobuf:"bytes,4,opt,name=type,proto3" json:"type,omitempty"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *Curve) Reset()         { *m = Curve{} }
func (m *Curve) String() string { return proto.CompactTextString(m) }
func (*Curve) ProtoMessage()    {}
func (*Curve) Descriptor() ([]byte, []int) {
	return fileDescriptor_4bd39486e62a5f01, []int{4}
}

func (m *Curve) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Curve.Unmarshal(m, b)
}
func (m *Curve) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Curve.Marshal(b, m, deterministic)
}
func (m *Curve) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Curve.Merge(m, src)
}
func (m *Curve) XXX_Size() int {
	return xxx_messageInfo_Curve.Size(m)
}
func (m *Curve) XXX_DiscardUnknown() {
	xxx_messageInfo_Curve.DiscardUnknown(m)
}

var xxx_messageInfo_Curve proto.InternalMessageInfo

func (m *Curve) GetEid() int32 {
	if m != nil {
		return m.Eid
	}
	return 0
}

func (m *Curve) GetId() int32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *Curve) GetCtype() Curve_CurveType {
	if m != nil {
		return m.Ctype
	}
	return Curve_UNKNOWN
}

func (m *Curve) GetType() string {
	if m != nil {
		return m.Type
	}
	return ""
}

type PulsePoint struct {
	T                    float32  `protobuf:"fixed32,1,opt,name=t,proto3" json:"t,omitempty"`
	Cid                  int32    `protobuf:"varint,2,opt,name=cid,proto3" json:"cid,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PulsePoint) Reset()         { *m = PulsePoint{} }
func (m *PulsePoint) String() string { return proto.CompactTextString(m) }
func (*PulsePoint) ProtoMessage()    {}
func (*PulsePoint) Descriptor() ([]byte, []int) {
	return fileDescriptor_4bd39486e62a5f01, []int{5}
}

func (m *PulsePoint) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PulsePoint.Unmarshal(m, b)
}
func (m *PulsePoint) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PulsePoint.Marshal(b, m, deterministic)
}
func (m *PulsePoint) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PulsePoint.Merge(m, src)
}
func (m *PulsePoint) XXX_Size() int {
	return xxx_messageInfo_PulsePoint.Size(m)
}
func (m *PulsePoint) XXX_DiscardUnknown() {
	xxx_messageInfo_PulsePoint.DiscardUnknown(m)
}

var xxx_messageInfo_PulsePoint proto.InternalMessageInfo

func (m *PulsePoint) GetT() float32 {
	if m != nil {
		return m.T
	}
	return 0
}

func (m *PulsePoint) GetCid() int32 {
	if m != nil {
		return m.Cid
	}
	return 0
}

type CircularLinearPoint struct {
	T                    float32                                `protobuf:"fixed32,1,opt,name=t,proto3" json:"t,omitempty"`
	Cid                  int32                                  `protobuf:"varint,2,opt,name=cid,proto3" json:"cid,omitempty"`
	X                    float32                                `protobuf:"fixed32,3,opt,name=x,proto3" json:"x,omitempty"`
	Y                    float32                                `protobuf:"fixed32,4,opt,name=y,proto3" json:"y,omitempty"`
	Type                 CircularLinearPoint_CircularLinearType `protobuf:"varint,5,opt,name=type,proto3,enum=curves.CircularLinearPoint_CircularLinearType" json:"type,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                               `json:"-"`
	XXX_unrecognized     []byte                                 `json:"-"`
	XXX_sizecache        int32                                  `json:"-"`
}

func (m *CircularLinearPoint) Reset()         { *m = CircularLinearPoint{} }
func (m *CircularLinearPoint) String() string { return proto.CompactTextString(m) }
func (*CircularLinearPoint) ProtoMessage()    {}
func (*CircularLinearPoint) Descriptor() ([]byte, []int) {
	return fileDescriptor_4bd39486e62a5f01, []int{6}
}

func (m *CircularLinearPoint) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CircularLinearPoint.Unmarshal(m, b)
}
func (m *CircularLinearPoint) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CircularLinearPoint.Marshal(b, m, deterministic)
}
func (m *CircularLinearPoint) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CircularLinearPoint.Merge(m, src)
}
func (m *CircularLinearPoint) XXX_Size() int {
	return xxx_messageInfo_CircularLinearPoint.Size(m)
}
func (m *CircularLinearPoint) XXX_DiscardUnknown() {
	xxx_messageInfo_CircularLinearPoint.DiscardUnknown(m)
}

var xxx_messageInfo_CircularLinearPoint proto.InternalMessageInfo

func (m *CircularLinearPoint) GetT() float32 {
	if m != nil {
		return m.T
	}
	return 0
}

func (m *CircularLinearPoint) GetCid() int32 {
	if m != nil {
		return m.Cid
	}
	return 0
}

func (m *CircularLinearPoint) GetX() float32 {
	if m != nil {
		return m.X
	}
	return 0
}

func (m *CircularLinearPoint) GetY() float32 {
	if m != nil {
		return m.Y
	}
	return 0
}

func (m *CircularLinearPoint) GetType() CircularLinearPoint_CircularLinearType {
	if m != nil {
		return m.Type
	}
	return CircularLinearPoint_UNKNOWN
}

type ColorPoint struct {
	T                    float32           `protobuf:"fixed32,1,opt,name=t,proto3" json:"t,omitempty"`
	Cid                  int32             `protobuf:"varint,2,opt,name=cid,proto3" json:"cid,omitempty"`
	C                    *ColorPoint_Color `protobuf:"bytes,3,opt,name=c,proto3" json:"c,omitempty"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *ColorPoint) Reset()         { *m = ColorPoint{} }
func (m *ColorPoint) String() string { return proto.CompactTextString(m) }
func (*ColorPoint) ProtoMessage()    {}
func (*ColorPoint) Descriptor() ([]byte, []int) {
	return fileDescriptor_4bd39486e62a5f01, []int{7}
}

func (m *ColorPoint) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ColorPoint.Unmarshal(m, b)
}
func (m *ColorPoint) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ColorPoint.Marshal(b, m, deterministic)
}
func (m *ColorPoint) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ColorPoint.Merge(m, src)
}
func (m *ColorPoint) XXX_Size() int {
	return xxx_messageInfo_ColorPoint.Size(m)
}
func (m *ColorPoint) XXX_DiscardUnknown() {
	xxx_messageInfo_ColorPoint.DiscardUnknown(m)
}

var xxx_messageInfo_ColorPoint proto.InternalMessageInfo

func (m *ColorPoint) GetT() float32 {
	if m != nil {
		return m.T
	}
	return 0
}

func (m *ColorPoint) GetCid() int32 {
	if m != nil {
		return m.Cid
	}
	return 0
}

func (m *ColorPoint) GetC() *ColorPoint_Color {
	if m != nil {
		return m.C
	}
	return nil
}

type ColorPoint_Color struct {
	R                    float32  `protobuf:"fixed32,1,opt,name=r,proto3" json:"r,omitempty"`
	G                    float32  `protobuf:"fixed32,2,opt,name=g,proto3" json:"g,omitempty"`
	B                    float32  `protobuf:"fixed32,3,opt,name=b,proto3" json:"b,omitempty"`
	A                    float32  `protobuf:"fixed32,4,opt,name=a,proto3" json:"a,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ColorPoint_Color) Reset()         { *m = ColorPoint_Color{} }
func (m *ColorPoint_Color) String() string { return proto.CompactTextString(m) }
func (*ColorPoint_Color) ProtoMessage()    {}
func (*ColorPoint_Color) Descriptor() ([]byte, []int) {
	return fileDescriptor_4bd39486e62a5f01, []int{7, 0}
}

func (m *ColorPoint_Color) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ColorPoint_Color.Unmarshal(m, b)
}
func (m *ColorPoint_Color) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ColorPoint_Color.Marshal(b, m, deterministic)
}
func (m *ColorPoint_Color) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ColorPoint_Color.Merge(m, src)
}
func (m *ColorPoint_Color) XXX_Size() int {
	return xxx_messageInfo_ColorPoint_Color.Size(m)
}
func (m *ColorPoint_Color) XXX_DiscardUnknown() {
	xxx_messageInfo_ColorPoint_Color.DiscardUnknown(m)
}

var xxx_messageInfo_ColorPoint_Color proto.InternalMessageInfo

func (m *ColorPoint_Color) GetR() float32 {
	if m != nil {
		return m.R
	}
	return 0
}

func (m *ColorPoint_Color) GetG() float32 {
	if m != nil {
		return m.G
	}
	return 0
}

func (m *ColorPoint_Color) GetB() float32 {
	if m != nil {
		return m.B
	}
	return 0
}

func (m *ColorPoint_Color) GetA() float32 {
	if m != nil {
		return m.A
	}
	return 0
}

type BasicPoint struct {
	T                    float32  `protobuf:"fixed32,1,opt,name=t,proto3" json:"t,omitempty"`
	Cid                  int32    `protobuf:"varint,2,opt,name=cid,proto3" json:"cid,omitempty"`
	X                    float32  `protobuf:"fixed32,3,opt,name=x,proto3" json:"x,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *BasicPoint) Reset()         { *m = BasicPoint{} }
func (m *BasicPoint) String() string { return proto.CompactTextString(m) }
func (*BasicPoint) ProtoMessage()    {}
func (*BasicPoint) Descriptor() ([]byte, []int) {
	return fileDescriptor_4bd39486e62a5f01, []int{8}
}

func (m *BasicPoint) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BasicPoint.Unmarshal(m, b)
}
func (m *BasicPoint) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BasicPoint.Marshal(b, m, deterministic)
}
func (m *BasicPoint) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BasicPoint.Merge(m, src)
}
func (m *BasicPoint) XXX_Size() int {
	return xxx_messageInfo_BasicPoint.Size(m)
}
func (m *BasicPoint) XXX_DiscardUnknown() {
	xxx_messageInfo_BasicPoint.DiscardUnknown(m)
}

var xxx_messageInfo_BasicPoint proto.InternalMessageInfo

func (m *BasicPoint) GetT() float32 {
	if m != nil {
		return m.T
	}
	return 0
}

func (m *BasicPoint) GetCid() int32 {
	if m != nil {
		return m.Cid
	}
	return 0
}

func (m *BasicPoint) GetX() float32 {
	if m != nil {
		return m.X
	}
	return 0
}

type MessagePoint struct {
	T                    float32  `protobuf:"fixed32,1,opt,name=t,proto3" json:"t,omitempty"`
	Cid                  int32    `protobuf:"varint,2,opt,name=cid,proto3" json:"cid,omitempty"`
	Msg                  string   `protobuf:"bytes,3,opt,name=msg,proto3" json:"msg,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MessagePoint) Reset()         { *m = MessagePoint{} }
func (m *MessagePoint) String() string { return proto.CompactTextString(m) }
func (*MessagePoint) ProtoMessage()    {}
func (*MessagePoint) Descriptor() ([]byte, []int) {
	return fileDescriptor_4bd39486e62a5f01, []int{9}
}

func (m *MessagePoint) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MessagePoint.Unmarshal(m, b)
}
func (m *MessagePoint) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MessagePoint.Marshal(b, m, deterministic)
}
func (m *MessagePoint) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MessagePoint.Merge(m, src)
}
func (m *MessagePoint) XXX_Size() int {
	return xxx_messageInfo_MessagePoint.Size(m)
}
func (m *MessagePoint) XXX_DiscardUnknown() {
	xxx_messageInfo_MessagePoint.DiscardUnknown(m)
}

var xxx_messageInfo_MessagePoint proto.InternalMessageInfo

func (m *MessagePoint) GetT() float32 {
	if m != nil {
		return m.T
	}
	return 0
}

func (m *MessagePoint) GetCid() int32 {
	if m != nil {
		return m.Cid
	}
	return 0
}

func (m *MessagePoint) GetMsg() string {
	if m != nil {
		return m.Msg
	}
	return ""
}

type VectorPoint struct {
	T                    float32  `protobuf:"fixed32,1,opt,name=t,proto3" json:"t,omitempty"`
	Cid                  int32    `protobuf:"varint,2,opt,name=cid,proto3" json:"cid,omitempty"`
	X                    float32  `protobuf:"fixed32,3,opt,name=x,proto3" json:"x,omitempty"`
	Y                    float32  `protobuf:"fixed32,4,opt,name=y,proto3" json:"y,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *VectorPoint) Reset()         { *m = VectorPoint{} }
func (m *VectorPoint) String() string { return proto.CompactTextString(m) }
func (*VectorPoint) ProtoMessage()    {}
func (*VectorPoint) Descriptor() ([]byte, []int) {
	return fileDescriptor_4bd39486e62a5f01, []int{10}
}

func (m *VectorPoint) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_VectorPoint.Unmarshal(m, b)
}
func (m *VectorPoint) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_VectorPoint.Marshal(b, m, deterministic)
}
func (m *VectorPoint) XXX_Merge(src proto.Message) {
	xxx_messageInfo_VectorPoint.Merge(m, src)
}
func (m *VectorPoint) XXX_Size() int {
	return xxx_messageInfo_VectorPoint.Size(m)
}
func (m *VectorPoint) XXX_DiscardUnknown() {
	xxx_messageInfo_VectorPoint.DiscardUnknown(m)
}

var xxx_messageInfo_VectorPoint proto.InternalMessageInfo

func (m *VectorPoint) GetT() float32 {
	if m != nil {
		return m.T
	}
	return 0
}

func (m *VectorPoint) GetCid() int32 {
	if m != nil {
		return m.Cid
	}
	return 0
}

func (m *VectorPoint) GetX() float32 {
	if m != nil {
		return m.X
	}
	return 0
}

func (m *VectorPoint) GetY() float32 {
	if m != nil {
		return m.Y
	}
	return 0
}

func init() {
	proto.RegisterEnum("curves.GameOverEvent_Team", GameOverEvent_Team_name, GameOverEvent_Team_value)
	proto.RegisterEnum("curves.Curve_CurveType", Curve_CurveType_name, Curve_CurveType_value)
	proto.RegisterEnum("curves.CircularLinearPoint_CircularLinearType", CircularLinearPoint_CircularLinearType_name, CircularLinearPoint_CircularLinearType_value)
	proto.RegisterType((*Element)(nil), "curves.Element")
	proto.RegisterType((*InitialDataEvent)(nil), "curves.InitialDataEvent")
	proto.RegisterType((*CreateEntityEvent)(nil), "curves.CreateEntityEvent")
	proto.RegisterType((*GameOverEvent)(nil), "curves.GameOverEvent")
	proto.RegisterType((*Curve)(nil), "curves.Curve")
	proto.RegisterType((*PulsePoint)(nil), "curves.PulsePoint")
	proto.RegisterType((*CircularLinearPoint)(nil), "curves.CircularLinearPoint")
	proto.RegisterType((*ColorPoint)(nil), "curves.ColorPoint")
	proto.RegisterType((*ColorPoint_Color)(nil), "curves.ColorPoint.Color")
	proto.RegisterType((*BasicPoint)(nil), "curves.BasicPoint")
	proto.RegisterType((*MessagePoint)(nil), "curves.MessagePoint")
	proto.RegisterType((*VectorPoint)(nil), "curves.VectorPoint")
}

func init() { proto.RegisterFile("curves_elements.proto", fileDescriptor_4bd39486e62a5f01) }

var fileDescriptor_4bd39486e62a5f01 = []byte{
	// 980 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xa4, 0x56, 0xdd, 0x6e, 0xe3, 0x44,
	0x14, 0x8e, 0xed, 0x38, 0x6d, 0x4f, 0x92, 0xe2, 0x4c, 0x29, 0x9b, 0x2d, 0x5c, 0xac, 0x2c, 0x40,
	0x2b, 0x58, 0x22, 0x35, 0x20, 0x81, 0x56, 0x42, 0x6c, 0xe2, 0x35, 0x9b, 0x88, 0xa4, 0xa9, 0xa6,
	0x69, 0xf7, 0xb2, 0x9a, 0x38, 0xb3, 0xce, 0x88, 0xd8, 0x8e, 0xec, 0x49, 0x76, 0xc3, 0x7b, 0xf0,
	0x10, 0xbc, 0x00, 0x17, 0x3c, 0x02, 0x2f, 0xc0, 0x63, 0xf0, 0x0a, 0x68, 0xc6, 0xff, 0x49, 0xa0,
	0x42, 0x7b, 0x93, 0x9c, 0x73, 0xbe, 0xef, 0x3b, 0x33, 0x73, 0xce, 0xfc, 0x18, 0xce, 0x9d, 0x75,
	0xb8, 0xa1, 0xd1, 0x3d, 0x5d, 0x52, 0x8f, 0xfa, 0x3c, 0xea, 0xac, 0xc2, 0x80, 0x07, 0xa8, 0x16,
	0x87, 0xcd, 0xbf, 0xab, 0x70, 0x64, 0xc7, 0x10, 0xfa, 0x11, 0x0c, 0xe6, 0x33, 0xce, 0xc8, 0xf2,
	0x25, 0xe1, 0xc4, 0xde, 0x50, 0x9f, 0xb7, 0x95, 0x27, 0xca, 0xd3, 0x7a, 0xb7, 0xdd, 0x89, 0xe9,
	0x9d, 0xe1, 0x0e, 0x3e, 0xa8, 0xe0, 0x3d, 0x0d, 0x1a, 0x42, 0xcb, 0x09, 0x29, 0xe1, 0xd4, 0xf6,
	0x39, 0xe3, 0xdb, 0x38, 0x91, 0x2a, 0x13, 0x3d, 0x4e, 0x13, 0x59, 0xbb, 0x84, 0x41, 0x05, 0xef,
	0xab, 0xd0, 0xf7, 0xd0, 0x74, 0x89, 0x47, 0x27, 0x1b, 0x1a, 0xc6, 0x69, 0x34, 0x99, 0xe6, 0x3c,
	0x4d, 0xf3, 0xaa, 0x08, 0x0e, 0x2a, 0xb8, 0xcc, 0x46, 0x9f, 0x81, 0x2e, 0x89, 0xed, 0xaa, 0x94,
	0x35, 0xb3, 0xd1, 0xc5, 0xdf, 0xa0, 0x82, 0x63, 0x14, 0x7d, 0x03, 0xb0, 0x5a, 0x2f, 0x23, 0x7a,
	0x1d, 0x30, 0x9f, 0xb7, 0x75, 0xc9, 0x45, 0x29, 0xf7, 0x3a, 0x43, 0x06, 0x15, 0x5c, 0xe0, 0xa1,
	0x09, 0x9c, 0x39, 0x2c, 0x74, 0xd6, 0x4b, 0x12, 0x8e, 0x98, 0x4f, 0x49, 0x18, 0xcb, 0x6b, 0x52,
	0xfe, 0x71, 0x36, 0xd4, 0x3e, 0x65, 0x50, 0xc1, 0x87, 0x94, 0x62, 0x1a, 0x4e, 0xb0, 0x0c, 0x92,
	0x3c, 0x47, 0xe5, 0x69, 0x58, 0x19, 0x22, 0xa6, 0x91, 0xf3, 0x84, 0x6a, 0x46, 0x22, 0xe6, 0xc4,
	0xaa, 0xe3, 0xb2, 0xaa, 0x9f, 0x21, 0x42, 0x95, 0xf3, 0xd0, 0xb7, 0x50, 0xdf, 0x50, 0x87, 0xa7,
	0x83, 0x9d, 0x48, 0xd9, 0x59, 0x2a, 0xbb, 0xcb, 0xa1, 0x41, 0x05, 0x17, 0x99, 0xe8, 0x39, 0x34,
	0x3c, 0x1a, 0x45, 0xc4, 0x4d, 0xaa, 0x05, 0x52, 0xf9, 0x61, 0xaa, 0x1c, 0x17, 0xb0, 0x41, 0x05,
	0x97, 0xb8, 0x7d, 0x0d, 0x14, 0x6a, 0xfe, 0xae, 0x81, 0xb1, 0xbb, 0x8d, 0xd0, 0x05, 0x1c, 0x7b,
	0x64, 0xf5, 0x9a, 0xcd, 0xf9, 0x42, 0x6e, 0x39, 0x15, 0x67, 0x3e, 0xfa, 0x04, 0x4e, 0x3c, 0xb2,
	0x1a, 0x50, 0xe6, 0x2e, 0xe2, 0x6d, 0xa4, 0xe2, 0x3c, 0x20, 0xd0, 0x75, 0x44, 0x43, 0x9f, 0x78,
	0xf4, 0x52, 0xee, 0x8e, 0x13, 0x9c, 0x07, 0x8a, 0x68, 0x57, 0x6e, 0x82, 0x02, 0xda, 0x45, 0x26,
	0x34, 0xc4, 0x7e, 0x79, 0xb9, 0x0e, 0x09, 0x67, 0x81, 0x2f, 0x3b, 0xaf, 0xe2, 0x52, 0x0c, 0x7d,
	0x04, 0xb5, 0x05, 0x25, 0x4b, 0xbe, 0x90, 0x0d, 0x51, 0x71, 0xe2, 0xa1, 0x67, 0xd0, 0xda, 0x30,
	0xfa, 0x96, 0xf9, 0x6e, 0x2f, 0xa4, 0x64, 0x44, 0x7d, 0x97, 0x2f, 0x64, 0x19, 0x55, 0xbc, 0x0f,
	0xa0, 0x2f, 0xc0, 0x28, 0x04, 0xe3, 0x75, 0x82, 0x24, 0xef, 0xc5, 0x77, 0x32, 0x4f, 0xde, 0xbc,
	0x89, 0x28, 0x6f, 0xd7, 0xf7, 0x32, 0xc7, 0x00, 0xfa, 0x4e, 0xb4, 0xdf, 0xf9, 0xd9, 0x0d, 0x83,
	0xb5, 0x3f, 0x6f, 0x37, 0xca, 0xc7, 0x35, 0xdf, 0x34, 0xb1, 0x89, 0x0b, 0x5c, 0xd4, 0x01, 0xe4,
	0xf7, 0xd7, 0xcb, 0x25, 0xe5, 0xd1, 0xd0, 0x1f, 0x13, 0x97, 0xfc, 0xc2, 0x7c, 0xda, 0x6e, 0x3e,
	0x51, 0x9e, 0xea, 0xf8, 0x00, 0x62, 0x8e, 0xa1, 0xb5, 0x77, 0x6a, 0x91, 0x01, 0x1a, 0x65, 0x73,
	0xd9, 0x33, 0x1d, 0x0b, 0x13, 0x21, 0xa8, 0xf2, 0xed, 0x8a, 0xca, 0x4e, 0x9d, 0x60, 0x69, 0xcb,
	0x18, 0x25, 0x5e, 0xd2, 0x1f, 0x69, 0x9b, 0x7f, 0x2a, 0xd0, 0x2c, 0x1d, 0x5f, 0xd4, 0x00, 0x85,
	0x27, 0xdd, 0x57, 0x38, 0xea, 0x42, 0xed, 0x2d, 0xf3, 0x7d, 0x1a, 0xca, 0x4c, 0xa7, 0xdd, 0x8b,
	0x83, 0x67, 0xbe, 0x33, 0xa5, 0xc4, 0xc3, 0x09, 0x13, 0x7d, 0x0a, 0xcd, 0x59, 0xc0, 0x2f, 0xad,
	0x90, 0x44, 0x8b, 0x29, 0xf3, 0xa8, 0x1c, 0x50, 0xc5, 0xe5, 0x60, 0xc2, 0xea, 0xe6, 0xac, 0x6a,
	0xc6, 0xca, 0x83, 0xe6, 0x97, 0x50, 0x15, 0xb9, 0x51, 0x1d, 0x8e, 0x6e, 0xaf, 0x7e, 0xba, 0x9a,
	0xbc, 0xbe, 0x32, 0x2a, 0x08, 0xa0, 0x36, 0xb5, 0x7b, 0xe3, 0xfb, 0x4b, 0x43, 0xc9, 0xec, 0xae,
	0xa1, 0x9a, 0xbf, 0xa9, 0xa0, 0xcb, 0x4b, 0xe5, 0x40, 0x41, 0x4e, 0x41, 0x65, 0x73, 0xb9, 0x08,
	0x1d, 0xab, 0x6c, 0x8e, 0xbe, 0x02, 0xdd, 0x91, 0x15, 0xd2, 0xe4, 0xba, 0x1e, 0x95, 0x2e, 0xa5,
	0xf8, 0x77, 0xba, 0x5d, 0x51, 0x1c, 0xb3, 0xb2, 0x7a, 0x56, 0xf3, 0x7a, 0x9a, 0x7f, 0x28, 0x70,
	0x92, 0x11, 0xcb, 0x33, 0x7c, 0x0c, 0xe7, 0xd6, 0x10, 0x5b, 0xb7, 0xa3, 0x1e, 0xbe, 0x1f, 0x0d,
	0xaf, 0xec, 0x1e, 0xbe, 0xb7, 0x6e, 0xf1, 0x9d, 0x6d, 0x28, 0xe8, 0x03, 0xa8, 0x5b, 0x93, 0xd1,
	0x24, 0x0d, 0xa8, 0xc8, 0x80, 0x46, 0x89, 0xa2, 0xa1, 0x47, 0x70, 0x96, 0x44, 0xee, 0x6c, 0x6b,
	0x9a, 0x51, 0xab, 0x42, 0x7b, 0x7d, 0x3b, 0xba, 0xb1, 0x93, 0x80, 0x8e, 0x4e, 0x01, 0x6e, 0xa6,
	0xf6, 0x75, 0xe2, 0xd7, 0xd0, 0x39, 0xb4, 0xa4, 0x5f, 0xd2, 0x1d, 0xa1, 0x16, 0x34, 0xc7, 0xf6,
	0xcd, 0x4d, 0xef, 0x55, 0xaa, 0x3c, 0x36, 0x9f, 0x01, 0xe4, 0x77, 0xea, 0x4e, 0xd3, 0x0d, 0xd0,
	0x9c, 0xac, 0x58, 0xc2, 0x34, 0xff, 0x52, 0xe0, 0xec, 0xc0, 0x1d, 0xfa, 0x90, 0x4e, 0xe0, 0xef,
	0x92, 0xf6, 0x2b, 0xef, 0x84, 0xb7, 0x4d, 0xda, 0xac, 0x6c, 0x51, 0x3f, 0x29, 0xa9, 0x2e, 0x1b,
	0xd0, 0xf9, 0x8f, 0xab, 0x7a, 0x27, 0x26, 0xfb, 0x12, 0xb7, 0xe0, 0x05, 0xa0, 0x7d, 0xac, 0xdc,
	0x0a, 0x1d, 0x94, 0x91, 0xa1, 0x88, 0x3f, 0xcb, 0x50, 0x51, 0x0d, 0x54, 0x6b, 0x6c, 0x68, 0xe8,
	0x08, 0x34, 0x6b, 0x6c, 0x19, 0x55, 0xf3, 0x57, 0x05, 0x20, 0x3f, 0xa0, 0x0f, 0x2e, 0xe8, 0x73,
	0x50, 0x9c, 0xe4, 0xf9, 0xfb, 0xf7, 0xf3, 0xad, 0x38, 0x17, 0x3f, 0x80, 0x2e, 0x6d, 0x91, 0x30,
	0x4c, 0x13, 0x4a, 0xcf, 0x4d, 0x6e, 0x4f, 0xc5, 0x15, 0xde, 0x2c, 0xad, 0xce, 0x4c, 0x78, 0x24,
	0xad, 0x0e, 0x31, 0x9f, 0x03, 0xe4, 0xcf, 0xc6, 0xff, 0xab, 0xb3, 0xf9, 0x02, 0x1a, 0xc5, 0x17,
	0xe0, 0x41, 0xb5, 0x01, 0x9a, 0x17, 0xb9, 0xc9, 0xbd, 0x20, 0x4c, 0x73, 0x08, 0xf5, 0xc2, 0xeb,
	0xf3, 0x3e, 0x6d, 0xee, 0x77, 0xe0, 0xc2, 0x09, 0xbc, 0x8e, 0x13, 0xcc, 0x99, 0xef, 0x2e, 0xc8,
	0x26, 0x70, 0x3a, 0x4b, 0x36, 0x4b, 0xbe, 0x80, 0xfa, 0x86, 0x3c, 0x40, 0xd1, 0x7c, 0x96, 0x7c,
	0xfe, 0x44, 0xb3, 0x9a, 0x04, 0xbe, 0xfe, 0x27, 0x00, 0x00, 0xff, 0xff, 0x0a, 0x4a, 0xe8, 0xfd,
	0x33, 0x09, 0x00, 0x00,
}
